[workspace]
resolver = "2"
members = [
    "2024/day-01",
    "2024/day-02",
    "2024/day-03",
    "2024/day-04",
    "2024/day-05",
    "2024/day-06",
    "2024/day-07",
    "2024/day-08",
    "2024/day-09",
    "2024/day-10",
    "aoc_utils",
]
