[package]
name = "day7"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
test-case = "1.2.1"
utils = { git = "https://github.com/matthew-e-brown/aoc-utils" }
lazy_static = "1.4.0"
regex = "1.5.4"
