[package]
name = "aoc_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
clap = { version = "4.5.23", features = ["derive"] }
scoped_threadpool = "0.1.9"
thiserror = "2.0.9"
