[package]
name = "day5c"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
test-case = "1.2.1"
utils = { path = "../../../rust-utils" }
